version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: url_shortener
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
